image: gitpod/workspace-full
FROM gitpod/workspace-full

# Install custom tools, runtime, etc.
RUN sudo apt-get update \
    && sudo apt-get install -y \
    geany geany-plugins synaptic meld \
    libgtk-3-dev libcurl4-gnutls-dev \
    libsdl2-dev libsdl2-mixer-dev libicu-dev \
    libgmp-dev libncurses5-dev xclip libwebsockets-dev
